# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - categories.md
  - about.md

footer: 'follow me on <a href="https://twitter.com/nikk0s3c">twitter</a> <a href="https://www.linkedin.com/in/nikhilanilkumar/">linkedin</a>'

style: dark # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
  - jekyll-figure
gems:
  - jekyll-figure
